# Generated by Django 6.0.3 on 2026-03-21 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SimulacaoEmprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=7)),
                ('juros', models.DecimalField(decimal_places=2, max_digits=5)),
                ('prazo', models.IntegerField()),
                ('parcela', models.DecimalField(decimal_places=2, max_digits=5)),
                ('valor_final', models.DecimalField(decimal_places=2, max_digits=7)),
                ('data_simulacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
