# Generated by Django 6.0.3 on 2026-03-25 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulador', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulacaoemprestimo',
            name='juros',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='simulacaoemprestimo',
            name='parcela',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='simulacaoemprestimo',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='simulacaoemprestimo',
            name='valor_final',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
